### PR TITLE
Cross env fix

### LINKED ISSUE #300: npm start for windows
As this `"start": "NODE_ENV=production node index.js"` does not work properly in windows.

Also stating about node version.

### PR DESCRIPTION
**Pull request by YashKumarVerma**
fix run script in windows

Fixes #300

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
pinging for review : @hereisnaman

**Comment by YashKumarVerma** [comment]
> package-lock.json is not required I guess

https://stackoverflow.com/a/44210813/5131640

**Comment by YashKumarVerma** [comment]
@ankiiitraj what's your discord username ?

**Comment by ankiiitraj** [comment]
ankiiitraj

**Comment by hereisnaman** [comment]
You also need to update the script I guess.

**Comment by YashKumarVerma** [comment]
Requesting someone to carry it forward.

**Pull request closed without merging**
