### PR TITLE
node version added and readme updated

### LINKED ISSUE #187: Add node and npm version in readme
There are lots of issue of people downloading wrong version of node and then creating new issue. Adding versions of these packages will help all developers.

### PR DESCRIPTION
**Pull request by farhan787**
fixes #187

### CODE REVIEW

**Comment by TheOneAboveAllTitan** [comment]
How did you came to know about node version? Was it a random guess?

**Comment by farhan787** [comment]
@TheOneAboveAllTitan most of the coding-blocks projects are running on version 8 and I also ran this with version 8 and it's working fine with it. That's how I figured out the node version.

**Comment by TheOneAboveAllTitan** [comment]
I appreciate your observance, don't you think we should update node to most recent LTS version? Generally speaking

**Comment by farhan787** [comment]
> I appreciate your observance, don't you think we should update node to most recent LTS version? Generally speaking

IMHO it should be updated, if you want it then I can make the changes for nvm.

**Comment by championswimmer** [comment]
I think this project works perfectly fine with Node 10
Let us use node 10, not 8

**Comment by farhan787** [comment]
> Let us use node 10, not 8

@championswimmer that's good idea, I'm doing that.

**Comment by farhan787** [comment]
@championswimmer done :-)

**Comment by farhan787** [comment]
@TheOneAboveAllTitan review please :-)

**Pull request closed without merging**
