### PR TITLE
Added conflicting claims section on accept claims page

### PR DESCRIPTION
**Pull request by prathambatra**
Signed-off-by: prathambatra <batrapratham999@gmail.com>

### CODE REVIEW

**Comment by prathambatra** [comment]
Screenshot from 2020-05-20 00-09-30
Screenshot from 2020-05-20 00-09-38
Screenshot from 2020-05-20 00-11-24
Screenshot from 2020-05-20 00-11-29
ezgif com-video-to-gif

**Comment by prathambatra** [comment]
fixes #260

**Comment by prathambatra** [comment]
@hereisnaman @championswimmer please review.

**Comment by YashKumarVerma** [comment]
> \hereisnaman \championswimmer please review.

image

**Comment by prathambatra** [comment]
thanks @YashKumarVerma

**Comment by hereisnaman** [comment]
@prathambatra can you fix the css. I see that is is problem with padding. Also please bring the Conflicting claims section below the update claim form. The form should go where the claim section is right now.

Or otherwise create a separate sidebar, but lets handle that in separate issue and bounty.

**Comment by prathambatra** [comment]
> @prathambatra can you fix the css. I see that is is problem with padding. Also please bring the Conflicting claims section below the update claim form. The form should go where the claim section is right now.
> 
> Or otherwise create a separate sidebar, but lets handle that in separate issue and bounty.

ok. so you mean I should replace places of update claim form and conflicted claims. right?

**Comment by hereisnaman** [comment]
> > @prathambatra can you fix the css. I see that is is problem with padding. Also please bring the Conflicting claims section below the update claim form. The form should go where the claim section is right now.
> > Or otherwise create a separate sidebar, but lets handle that in separate issue and bounty.
> 
> ok. so you mean I should replace places of update claim form and conflicted claims. right?

Yes and fix the padding and other styles for claim section.

**Comment by prathambatra** [comment]
> > > @prathambatra can you fix the css. I see that is is problem with padding. Also please bring the Conflicting claims section below the update claim form. The form should go where the claim section is right now.
> > > Or otherwise create a separate sidebar, but lets handle that in separate issue and bounty.
> > 
> > 
> > ok. so you mean I should replace places of update claim form and conflicted claims. right?
> 
> Yes and fix the padding and other styles for claim section.

Yeah sure

**Comment by prathambatra** [comment]
Screenshot from 2020-05-22 15-58-56
@hereisnaman

**Comment by prathambatra** [comment]
Is this fine? should I commit it?

**Comment by hereisnaman** [comment]
> Is this fine? should I commit it?

Can you not see there is padding issue in the conflict item header. Does a good UI element has such basic issues?

**Comment by prathambatra** [comment]
Screenshot from 2020-05-22 20-19-22
Fixed padding in card header. Replaced the position of conflicting claims and form.

**Comment by prathambatra** [comment]
@hereisnaman ?

**Comment by prathambatra** [comment]
please see #357

**Pull request closed without merging**
