### PR TITLE
Add CB Bootstrap Theme

### LINKED ISSUE #287: use cb bootstrap theme
- semantic ui isn't well maintained anymore (fomantic exists, but nevertheless)
- we have our own branded bootstrap edition - https://bootstrap.codingblocks.in

we will move the entire frontend (i.e. hbs pages) to cb's bootstrap and remove all semantic/fomantic stuff

### PR DESCRIPTION
**Pull request by kushaggarwal**
Closes #287 
This PR aims at the addition of the CB Bootstrap theme to the current BOSS Site

### CODE REVIEW

**Comment by championswimmer** [comment]
UI changes must be accompanied by screenshots.

**Comment by championswimmer** [comment]
Also do not pull the static assets of theme here. Link to the cdns.

**Comment by kushaggarwal** [comment]
Okay 
Will update the following 
Thanks

**Comment by kushaggarwal** [comment]
Images for desktop view for BOSS
Screenshot 2020-05-20 at 6 53 58 PM
Screenshot 2020-05-20 at 6 53 52 PM
Screenshot 2020-05-20 at 6 53 48 PM
Screenshot 2020-05-20 at 6 53 35 PM
Screenshot 2020-05-20 at 6 53 26 PM
Screenshot 2020-05-20 at 6 53 16 PM
Screenshot 2020-05-20 at 6 53 05 PM
Screenshot 2020-05-20 at 6 52 58 PM

**Comment by kushaggarwal** [comment]
Images for Mobile View for BOSS
Screenshot 2020-05-20 at 7 03 15 PM
Screenshot 2020-05-20 at 7 03 07 PM
Screenshot 2020-05-20 at 7 02 38 PM
Screenshot 2020-05-20 at 7 03 00 PM
Screenshot 2020-05-20 at 7 02 56 PM
Screenshot 2020-05-20 at 7 02 49 PM
Screenshot 2020-05-20 at 7 04 52 PM

**Comment by championswimmer** [comment]
This is looking pretty good. Will do one final round of testing

**Comment by championswimmer** [comment]
semantic should be uninstalled from package.json and semantic files and folders should be cleaned too

**Comment by kushaggarwal** [comment]
Okay 
Thank you very much for your feedback 
Will update the following

**Comment by kushaggarwal** [comment]
I have updated the icons and cleaned up the files related to semantic/fomantic but upon running npm start the semantic folder rebuilds again 
So, can you please help how to proceed on this 
Thanks

**Comment by championswimmer** [comment]
you need to uninstall semantic and removee the prestart script

**Comment by kushaggarwal** [comment]
Okay will update the  following

**Comment by kushaggarwal** [comment]
Please find the updated request for the changes mentioned above
Thanks

**Comment by championswimmer** [comment]
remove ds store and shrinkwrap files please

**Comment by kushaggarwal** [comment]
Please find the above request in reference to removel of DS Store and shrinkwrap file

**Pull request closed without merging**
