### PR TITLE
fixes #270 - fixed unpleasant behaviour of footer

### LINKED ISSUE #270: Footer is not proper
Capture

### PR DESCRIPTION
**Pull request by ankiiitraj**
Fixed #270 - Removed position fixed attribute and made the social icons in a row and can wrap on small sccreens

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Hi @hereisnaman please review the code. Thanks

**Comment by hereisnaman** [comment]
Please add screenshots

**Comment by ankiiitraj** [comment]
position is not fixed now rather we we reach the end of the page we can see footer . . .
Screenshot from 2020-05-18 20-07-56

**Comment by ankiiitraj** [comment]
Position is not fixes now rather we have togo to end to see the footer
Screenshot from 2020-05-18 20-07-56

**Comment by hereisnaman** [comment]
footer has been removed

**Pull request closed without merging**
