### PR TITLE
added responsive menu

### PR DESCRIPTION
**Pull request by architkshk**
#59

### CODE REVIEW

**Comment by championswimmer** [comment]
please resolve conflicts and add before/after screenshots

**Comment by architkshk** [comment]
Before -

screenshot from 2018-05-19 07-41-22

 
After - 
screenshot from 2018-05-19 07-44-55


screenshot from 2018-05-19 07-42-34

**Comment by architkshk** [comment]
Will also resolve #74

**Comment by ananay** [comment]
@architkshk There are many more improvements I've made to the responsiveness and not just the menu because they were essential.

**Pull request merged**
