### PR TITLE
Fixes #251 - Show Rank and Your Rank on leaderboard

### LINKED ISSUE #251: Show Rank and "Your Rank" on leaderboard
- [x] Show Ranks on leaderboard.
- [x] If user is logged in show "Your Rank" on top of leaderboard and then the reset of the leaderboard. Similar to the leaderboard shown on [Hackerblocks](https://hack.codingblocks.com/app/)

### PR DESCRIPTION
**Pull request by ankiiitraj**
Fixes #251 - Added column for Rank and Rank of loggedIn user shows on top

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Hi @hereisnaman - Apologies for late PR as I was figuring out things as I am new to ember and sequalize.
Here are the screenshots
Screenshot from 2020-05-19 13-05-28
Screenshot from 2020-05-19 13-10-03

**Comment by hereisnaman** [comment]
No need at add the 'You' text. All the requirements mentioned here https://github.com/coding-blocks/boss/issues/251#issuecomment-630579658 are not followed.

**Comment by ankiiitraj** [comment]
Updating the PR soon

**Comment by hereisnaman** [comment]
Issue has been fixed

**Pull request closed without merging**
