### PR TITLE
Added testing command and fixed README

### PR DESCRIPTION
**Pull request by ananay**
After a lot of debugging, I noticed that it all boiled down to this: Node's "BOSS_ENV === 'localhost'" was returning false. The test commands were incorrectly specific in the documentation. I've made a separate script in the package.json to start the testing server and I've written about it clearly in the README.md file. 

image

### CODE REVIEW

**Comment by ananay** [comment]
Fixes #91

**Comment by championswimmer** [comment]
err, why not just

```
BOSS_DEV=localhost npm run test
```

**Comment by championswimmer** [comment]
mocha already runs the server while testing (check the  before() function)

**Comment by ananay** [comment]
@championswimmer There was an error in mocha's before function. Basically, everything was supposed to run on port 3232 but only the test server in mocha's before function was running on port 8000. This caused all the issues that we were facing. I've changed the port back to 3232 and everything is working as intended using ````"BOSS_DEV='localhost'"```` and the ````"npm run test"```` command only.

image

**Comment by ananay** [comment]
@championswimmer Why didn't you merge this?

**Pull request closed without merging**
