### PR TITLE
Adding repository metadata

### LINKED ISSUE #209: Github repository meta documents missing
The following documents are missing and should be added to validate the open source project and structure a community.

- [ ] Pull Request Template
- [ ] Issue Template
- [ ] Contributing Guidelines
- [ ] Code Of conduct

Working on it, claiming.

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Fixes #209 

- [x] Pull Request Template
- [x] Issue Template
- [x] Contributing Guidelines
- [x] Code Of conduct

awaiting triage for BOSS bounty

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
pinging @championswimmer

**Comment by championswimmer** [comment]
Issue and PR template looks too strict. We can let that go .

**Comment by championswimmer** [comment]
"Write tests" in contributing guidelines doesn't make sense. This repo has no tests, no one would be able to add tests in initial PRs in current state.

**Comment by YashKumarVerma** [comment]
Should we close it then ?

**Comment by YashKumarVerma** [comment]
Requesting someone to carry it forward.

**Pull request closed without merging**
