### PR TITLE
fixes #221 - Added hover effects to nav links

### LINKED ISSUE #221: add  navigation bar hover effects animation
image
There is no hover effect in the submenu of navbar adding it will look great in UI

### PR DESCRIPTION
**Pull request by ankiiitraj**
fixes #221 - Added hover effects to nav links

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Hi @abhishek97  can you review this please

**Comment by hereisnaman** [comment]
PRs without screenshots will not be reviewed.

**Comment by ankiiitraj** [comment]
Hi I have uploaded the preview
Screenshot from 2020-05-18 22-17-11

**Comment by ankiiitraj** [comment]
Follow up: If there some more changes are to be done let me know

**Pull request merged**
