### PR TITLE
fixes #299 - Fixed edit functionality which wasnt functional

### LINKED ISSUE #299: Save button do not saves the changes on Edit page
Steps to reproduce:
1. Add a claim and save
2. Click on edit option for your claim.
3. Make the changes and hit save.

What was expected
      Changes should be visible on the claims page
What is happening
     Changes are not shown rather previous data is shown

### PR DESCRIPTION
**Pull request by ankiiitraj**
Fixed #299 
Problem was update function was configured for only admin.
Now the functionality to edit and save works fine

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Hi @hereisnaman , Kindly review this PR and let me know if something is to be done. Thanks

**Comment by ankiiitraj** [comment]
Hi @hereisnaman , this has been sitting for more than 2 days now, Kindly review

**Comment by ankiiitraj** [comment]
Kindly review this too @hereisnaman

**Comment by hereisnaman** [comment]
@ankiiitraj no need to enable update for the urls. Rather disable the input fields in the edit form on frontend.

**Comment by ankiiitraj** [comment]
Done :)

**Pull request closed without merging**
