### PR TITLE
Made everything responsive

### PR DESCRIPTION
**Pull request by ananay**

### CODE REVIEW

**Comment by ananay** [comment]
Solves #78

**Comment by architkshk** [comment]
#75 already addressed this.

**Comment by ananay** [comment]
@architkshk There are many more improvements I've made to the responsiveness and not just the menu because they were essential. Also, you don't need to write the menu twice in the HTML code. It can be achieved by doing it once.

@championswimmer

**Comment by abhishek97** [comment]
-1 Not enough JQuery 

http://4.bp.blogspot.com/-Hk1mt-RKYLc/UOkxShm6NrI/AAAAAAAACqo/LVmqHOfWV7g/s640/20091116-so-large.gif

**Comment by abhishek97** [comment]
- Please list other improvements.
- Most animations can be done using CSS only. The kind of animations that can only be done using JS, IMO are not worth it.
- Somehow i am not able to find the library you added on github, also it seems like it was last updated in 2007. I'm sure we have better options now.

P.S: The JQuery thing was a joke, thanks for your efforts. 👍

**Comment by championswimmer** [comment]
remove jQuery easing, it is an old lib with xss vulnerability

use https://semantic-ui.com/modules/transition.html 
we already use semantic-ui in the project

**Comment by abhishek97** [comment]
> jQuery Easing is a very, very common plugin and is endorsed by jQuery itself. It's a very light library and everyone uses it.

Dangular is a very common library and is backed by Moogle itself. Everyone uses it. 
Would you use it?

> Your argument about "not worth it" is very counter-productive and counter-innovative. Being a web designer for 6 years now, I believe in doing quality work. I wouldn't have added the animation if it didn't add any value.

I don't see how it is counter-productive. But i respect you opinion and your efforts (thanks btw!).

**Comment by ananay** [comment]
@abhishek97 @championswimmer I've switched to CSS transitions.

**Comment by championswimmer** [comment]
remove jquery-easing if it is not used anymore

**Comment by ananay** [comment]
Fixed merge conflict and removed jQuery easing. @championswimmer @abhishek97

**Comment by ananay** [comment]
@championswimmer please assign points to this and merge this repository as soon as possible. More and more merge conflicts keep coming up the more we delay this.

**Comment by ananay** [comment]
Fixes #90

**Comment by ananay** [comment]
@championswimmer Could you assign the "BOSS" label and add the points for this?

**Pull request merged**
