### PR TITLE
fixed highlight

### LINKED ISSUE #366: Improper highlight box
Highlight box radius is inconsistent.
http://boss.codingblocks.com/claims/view

Screenshot:

### PR DESCRIPTION
**Pull request by gurrrung**
closes #366 
Removed unwanted blue highlight on focus.

Screenshot from 2020-05-28 20-07-05

### CODE REVIEW

**Comment by mnb27** [comment]
I think removing it is not a solution. We can adjust the ouline.

**Comment by gurrrung** [comment]
How should the final one look like?

**Comment by gurrrung** [comment]
I thought we don't even need it, looks very distracting.

**Comment by mnb27** [comment]
@championswimmer @hereisnaman The highlight should be removed or adjusted ?

**Comment by gurrrung** [comment]
By the way, adding to this discussion. It is currently not supported in all the browsers to add a radius to the outline. https://stackoverflow.com/questions/5394116/outline-radius
Further, there is already a clicking effect on the button which is sufficient. Let's see what the maintainers have to say.

**Comment by championswimmer** [comment]
I don't see an issue with whatever it is right now.

**Pull request closed without merging**
