### PR TITLE
Boss Mobile navbar made more responsive issue#214

### PR DESCRIPTION
**Pull request by aannaassalam**
I made the navbar of boss website for mobile more reponsive and here are the ScreenShot of those.
Annotation 2020-05-24 004352
Annotation 2020-05-24 004251

@championswimmer @abhishek97 @hereisnaman please review this 
Fix for issue #214

### CODE REVIEW

**Comment by hereisnaman** [comment]
@aannaassalam can you add a gif or loom recording?

**Comment by hereisnaman** [comment]
Also remove `public_path` and `semantic.json` changes from diff. Have you tested these changes cross browsers?

**Comment by aannaassalam** [comment]
Can you please help me to remove those changes

**Comment by hereisnaman** [comment]
> Can you please help me to remove those changes

if you are on the latest version of git the following should work:
```bash
git reset --soft HEAD~1
git restore -S -W -s HEAD public_static semantic.json
```

**Comment by aannaassalam** [comment]
Ok I am giving it a try

**Comment by aannaassalam** [comment]
ezgif com-video-to-gif
This is the GIF of the preview 

and I made the nessesary changes that you demanded for.
 please see to it @hereisnaman

**Comment by hereisnaman** [comment]
@aannaassalam basically I wanted to see how the leaderboard and claims dropdown are behaving. Can you display that.

**Comment by aannaassalam** [comment]
Offcourse are you comfortable with the changes removed in public_static and semantic as u asked 
Is it Ok???

**Comment by hereisnaman** [comment]
> Offcourse are you comfortable with the changes removed in public_static and semantic as u asked
> Is it Ok???

I can still see they are not removed from the diff https://github.com/coding-blocks/boss/pull/344/files

**Comment by aannaassalam** [comment]
Ok I am fixing them and also sending you the response of leaderboard and claim option too

**Comment by aannaassalam** [comment]
ezgif com-video-to-gif
I removed the public_static and semantic.json commit and above is the GIF that you requested for.
please give your reviews that you are impressed or not

**Pull request merged**
